"""Replace full_name with username and add role column

Revision ID: 963827028f31
Revises: 
Create Date: 2026-08-12 17:19:45.078590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963827028f31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('order_items_quantity_check'), type_='check')
        batch_op.drop_constraint(batch_op.f('order_items_unit_price_check'), type_='check')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('products_price_check'), type_='check')
        batch_op.drop_constraint(batch_op.f('products_stock_quantity_check'), type_='check')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=50), server_default='customer', nullable=False))
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('role')
        batch_op.drop_column('username')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('products_stock_quantity_check'), 'stock_quantity >= 0')
        batch_op.create_check_constraint(batch_op.f('products_price_check'), 'price >= 0::numeric')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('order_items_unit_price_check'), 'unit_price >= 0::numeric')
        batch_op.create_check_constraint(batch_op.f('order_items_quantity_check'), 'quantity > 0')

    # ### end Alembic commands ###
